# NumPy
Welcome to the fourth lesson! This Jupyter Notebook file is meant to accompany **L04 - NumPy.**

Type your solutions for each exercise in the code cells below, and then press **Shift + Enter** to execute your code. Then, check the solution video to see how you did!

### 1. Introduction to NumPy

### 2. NumPy Arrays

In [1]:
# import modules
import numpy as np


<font color = 'blue'> **EXERCISE 2.1** </font>

In [2]:
import math
math.log(10)

2.302585092994046

In [3]:
array_1 = np.array([1, 2, 'three', 4.0])
print(type(array_1))
print(array_1)

<class 'numpy.ndarray'>
['1' '2' 'three' '4.0']


In [4]:
array_2 = np.array([1, 2, 3.0, 4])
print(type(array_2))
print(array_2)

<class 'numpy.ndarray'>
[1. 2. 3. 4.]


In [5]:
# Recreate table as NP Array

array2_1 = np.array([[1,2],[3,4], [5,6]])
print(array2_1)
print(f'shape: {array2_1.shape}')
print(f'type: {type(array2_1)}')

[[1 2]
 [3 4]
 [5 6]]
shape: (3, 2)
type: <class 'numpy.ndarray'>


In [6]:
# Reshape to 2 rows and 3 col.

print(f' temporary reshape: \n{array2_1.reshape(2,3)}')
print('---')
print(f'origninal shape: \n{array2_1}')
print('---')

# for perm. reshape, must assign to a variable
array2_1 = array2_1.reshape(2,3)
print(f'perm reshape: \n{array2_1}')


 temporary reshape: 
[[1 2 3]
 [4 5 6]]
---
origninal shape: 
[[1 2]
 [3 4]
 [5 6]]
---
perm reshape: 
[[1 2 3]
 [4 5 6]]


In [7]:
# Selecting items in an array

# build array
array_x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# Select the 6
array_x[1,2] # Second row (index 1), third column (index 2)


np.int64(6)

In [8]:
# Selecting a range in an array

# build the array
array_y = np.array([
    [1,2,3],
    [4,5,6]
])

# Select 1,2,4,5
# first range is the range of rows. first index is what to include, second is the first to exclude.  Only 2 rows so include all.
# Second range is the range of columns.  Same method. first includes, second is the first column to exclude.
print(array_y[0:, 0:2])

[[1 2]
 [4 5]]


<font color = 'blue'> **EXERCISE 2.2** </font>

In [9]:
array_a = np.array([
    ['n', 'e', 'w', 'y', '_', 's'],
    ['t', 'o', 'c', 'k', '_', 'r'],
    ['_', '_', '_', 'k', 'e', 'x'],
    ['c', 'h', 'a', 'n', 'g', 'e']
])
array_a

array([['n', 'e', 'w', 'y', '_', 's'],
       ['t', 'o', 'c', 'k', '_', 'r'],
       ['_', '_', '_', 'k', 'e', 'x'],
       ['c', 'h', 'a', 'n', 'g', 'e']], dtype='<U1')

In [10]:
# Reshape to 6 rows and 4 columns and print

array_b = array_a.reshape(6,4)
array_b

array([['n', 'e', 'w', 'y'],
       ['_', 's', 't', 'o'],
       ['c', 'k', '_', 'r'],
       ['_', '_', '_', 'k'],
       ['e', 'x', 'c', 'h'],
       ['a', 'n', 'g', 'e']], dtype='<U1')

In [13]:
print(array_b[0, :3])     # new
print(array_b[:4, 3])     # york
print(array_b[1, 1:], array_b[2,:2])  # stock
print(array_b[4, :], array_b[5, :])    # exchange



['n' 'e' 'w']
['y' 'o' 'r' 'k']
['s' 't' 'o'] ['c' 'k']
['e' 'x' 'c' 'h'] ['a' 'n' 'g' 'e']


### 3. NumPy Array Functions

<font color = 'blue'> **EXERCISE 3.1** </font>

In [16]:
# Playground for calculations

array_m = np.array([
    [1,2],
    [3,4]
])

array_n = np.array([
    [5,6],
    [7,8]
])

array_o = array_n + array_m
# array_o

array_z = array_o +10
array_z


array([[16, 18],
       [20, 22]])

In [17]:
# Useful Numpy Functions (when using with arrays, these must be used, not the python equivalent)

# np.round()
# np.sqrt()
# np.abs()
# np.power()
# many others as well

# square root example
root_z = np.sqrt(array_z)
root_z

array([[4.        , 4.24264069],
       [4.47213595, 4.69041576]])

In [19]:
# round the root

round_root_z = np.round(root_z, 2)
round_root_z

array([[4.  , 4.24],
       [4.47, 4.69]])

In [24]:
# Numpy aggregation functions
# np.sum()
# np.min()
# np.max()
# np.median()
# np.mean()
# np.std()

print(array_z)
print('---')
print('Sum of all objects = {}'.format(np.sum(array_z), axis=0)) # axis = 0 => sum the columns, axis = 1 => sum of rows
print('Min = {}'.format(np.min(array_z)))
print('Max = {}'.format(np.max(array_z)))

[[16 18]
 [20 22]]
---
Sum of all objects = 76
Min = 16
Max = 22


![exercise 3.1](images/exercise3-1.png)

In [21]:
companies = np.array([
    ['Tech', 'Financials', 'Healthcare'],
    ['AAPL', 'JPM', 'JNJ'],
    ['MSFT', 'BAC', 'UNH'],
    ['FB', 'WFC', 'PFE']
])

current_prices = np.array([
    [223.84, 113.5, 139.49],
    [113.37, 30.37, 265.31],
    [1177.98, 54.73, 42.96],
])

target_prices = np.array([
    [232.27, 112.15, 144.2],
    [122.3, 34.33, 284.14],
    [1384.89, 62.12, 43.06],
]) 

In [22]:
price_increases = target_prices - current_prices
price_increases

array([[ 8.4300e+00, -1.3500e+00,  4.7100e+00],
       [ 8.9300e+00,  3.9600e+00,  1.8830e+01],
       [ 2.0691e+02,  7.3900e+00,  1.0000e-01]])

In [23]:
returns = price_increases / current_prices
returns

array([[ 0.03766083, -0.01189427,  0.03376586],
       [ 0.07876863,  0.13039183,  0.07097358],
       [ 0.17564814,  0.13502649,  0.00232775]])

In [30]:
print(type(companies[0:1,0:1]))
print(companies[0:1,0:1])

<class 'numpy.ndarray'>
[['Tech']]


In [31]:
print(type(companies[0:1,0:1]))
print(type(companies[0,0]))

<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [39]:
max_return = np.max(returns)
print(f'Max Return: ${max_return}')
print('---')

mean_returns = np.mean(returns, axis=0) # calculates the mean of each column separately
rounded_mean_returns = np.round(mean_returns, 3)

# create list of company industries
company_industries = companies[0] # places entire np array row at index 0 into a list

# using `zip` creates a list of tuples
summary_mean_returns = list(zip(company_industries, rounded_mean_returns))

print("Mean Return by Industry")
summary_mean_returns


Max Return: $0.17564814343197685
---
Mean Return by Industry


[(np.str_('Tech'), np.float64(0.097)),
 (np.str_('Financials'), np.float64(0.085)),
 (np.str_('Healthcare'), np.float64(0.036))]

### 4. NumPy Random Tools

<font color = 'blue'> **EXERCISE 4.1** </font>