# NumPy
Welcome to the fourth lesson! This Jupyter Notebook file is meant to accompany **L04 - NumPy.**

Type your solutions for each exercise in the code cells below, and then press **Shift + Enter** to execute your code. Then, check the solution video to see how you did!

In [1]:
import numpy as np

### 1. Introduction to NumPy

In [4]:
# Working area
array_01 = np.array([1,2,3,4,5])
print(type(array_01))

array_01

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

### Important Note:
- In the array below, note that the array was set up with integers and one string
- What was returned was all strings though
- This means that this array cannot use the values as they are now strings.

In [5]:
array_02 = np.array([1,2,"three",4,5])

print(array_02)

['1' '2' 'three' '4' '5']


#### Notes
- The below array is a 2-dimensional array.  To create multi-dimensional arrays, the lists must be in a list of lists:  format -- ( [ [ ], [ ] ] ).  If not in this format, numpy will throw an error.
- To find the shape use variable.shape  # [ num_rows, num_columns ]


In [8]:
array_03 = np.array([[1,2,3],[4,5,6]])
print(f"Array 03: ", array_03)
print(f"shape: ", array_03.shape)

Array 03:  [[1 2 3]
 [4 5 6]]
shape:  (2, 3)


### 2. NumPy Arrays

<font color = 'blue'> **EXERCISE 2.1** </font>

## Instructions
create the following array:
- 1, 2
- 3, 4
- 5, 6
- print the array, then the dimensions

In [9]:
array_2_1 = np.array([[1,2], [3,4], [5,6]])
print(f"array_2_1: \n", array_2_1)
print(f"Shape: ", array_2_1.shape)

array_2_1: 
 [[1 2]
 [3 4]
 [5 6]]
Shape:  (3, 2)


#### How to reshape the array
- use reshape method:
    - variable.reshape(num_rows, num_columns)
        - The num_rows and num_columns are the new shape desired
    - **numpy.reshape() does not modify the original array in-place — it returns a new reshaped array.**
        - Either print directly or save to another variable

- Transpose
- transpose: Swaps axes (like flipping rows & columns)
Think of it like rotating or flipping the array across its diagonal — it doesn't reshape arbitrarily, it specifically swaps axes.

In [15]:
# reshape exercise 2.1 to be 2 rows and 3 columns
array_2_1 = array_2_1.reshape(3,2)
array_2_1_reshape = array_2_1.reshape(2, 3)
print(array_2_1_reshape)

[[1 2 3]
 [4 5 6]]


In [17]:
# Try Transpose and note the differences in output
array_2_1_transpose = array_2_1.T
print(array_2_1_transpose)

[[1 3 5]
 [2 4 6]]


#### Accessing values in arrays
- same as with lists, but there is another dimension.  variable[row_index, column_index]
- See figure for following example:  ![np index](figures/numpy_array_indexing.png)
- to find the 6 in array_01
- array_01[1, 2]

### Accessing a range of values
- Given the following array:  [np_array_for_range_indexing](figures/np_array_range_indexing.png)
- array_01[0:2, 0:2]

<font color = 'blue'> **EXERCISE 2.2** </font>

## Instructions
- create a new array, array_b, and reshape it to 6 rows, 4 columns
- print array_b
- using ranges, print "new york stock exchange" making a new line every time you create a new word

In [18]:
array_a = np.array([
    ['n', 'e', 'w', 'y', '_', 's'],
    ['t', 'o', 'c', 'k', '_', 'r'],
    ['_', '_', '_', 'k', 'e', 'x'],
    ['c', 'h', 'a', 'n', 'g', 'e']
])

In [20]:
# Reshape to 6 rows and 4 columns and print
b = array_a.reshape(6, 4)
print(array_b)


[['n' 'e' 'w' 'y']
 ['_' 's' 't' 'o']
 ['c' 'k' '_' 'r']
 ['_' '_' '_' 'k']
 ['e' 'x' 'c' 'h']
 ['a' 'n' 'g' 'e']]


In [30]:
# Print 'new york stock exchange' from array_b (one word per line)
new = b[0:1, 0:3]
print(new)

york = b[0:4, 3:4]
york = york.reshape(1,4)
print(york)

sto = b[1:2, 1:]
ck = b[2:3, :2]
stock = np.concatenate([sto, ck], axis=1)  # horizontal
print(stock)

exch = b[4:5, 0:]
ange = b[5:6, 0:]
exchange = np.concatenate([exch, ange], axis=1)
print(exchange)


[['n' 'e' 'w']]
[['y' 'o' 'r' 'k']]
[['s' 't' 'o' 'c' 'k']]
[['e' 'x' 'c' 'h' 'a' 'n' 'g' 'e']]


### 3. NumPy Array Functions

<font color = 'blue'> **EXERCISE 3.1** </font>

#### Tables
![exercise_3_1_tables](figures/exercise_3_1_table.png)

## Instructions
![instructions](figures/exercise_3_1_instructions.png)

In [31]:
current_prices = np.array([
    [223.84, 113.5, 139.49],
    [113.37, 30.37, 265.31],
    [1177.98, 54.73, 42.96],
])

target_prices = np.array([
    [232.27, 112.15, 144.2],
    [122.3, 34.33, 284.14],
    [1384.89, 62.12, 43.06],
])

companies = np.array([
    ['AAPL', 'JPM', 'JNJ'],
    ['MSFT', 'BAC', 'UNH'],
    ['FB', 'WFC', 'PFE']
])

In [37]:
# Create price increases
price_increases = target_prices - current_prices
print(np.round(price_increases, 3))

[[ 8.4300e+00 -1.3500e+00  4.7100e+00]
 [ 8.9300e+00  3.9600e+00  1.8830e+01]
 [ 2.0691e+02  7.3900e+00  1.0000e-01]]


In [36]:
# Create returns
returns = price_increases / current_prices
print(np.round(returns, 3))

[[ 0.038 -0.012  0.034]
 [ 0.079  0.13   0.071]
 [ 0.176  0.135  0.002]]


In [41]:
# max value in return
max_return = np.max(returns)
print(f"Max Return: ", round(max_return, 3))

mean_return = np.mean(returns, axis=0)
print(f"mean by industry: ", np.round(mean_return, 3))

Max Return:  0.176
mean by industry:  [0.097 0.085 0.036]


### 4. NumPy Random Tools

Working cells
- use of random function in numpy np.random.randint(low=1, high=11, size=10)
- if you want to hold the random numbers, then use variable.random.seed(random integers)
- To make random numbers unique, add *replace=False* to the argument


In [55]:
np.random.seed(12)

random = np.random.randint(low=1, high=11, size=(5,2))
print(random)

[[7 2]
 [3 4]
 [4 1]
 [7 2]
 [5 6]]


In [56]:
ordered_array = np.array(range(1, 11))
ordered_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
np.random.seed(10)
print(np.random.choice(ordered_array, 5, replace=False))

[9 3 6 7 4]


<font color = 'blue'> **EXERCISE 4.1** </font>

## Instructions
![Instructions](figures/exercise_4_1_instructions.png)

![instructions continued](figures/exercise4_1_continued.png)

In [71]:
np.random.seed(99)  # For reproducibility

rand_array = np.array(range(1, 26))       # Ordered numbers 1 to 25
np.random.shuffle(rand_array)             # In-place shuffle
rand_array = rand_array.reshape(5, 5)     # Reshape into 5x5 matrix

print(rand_array)

[[11 18 13 21 22]
 [ 3 20 14  7  1]
 [12 17 16 24 15]
 [ 8 25  6  5 19]
 [23 10  9  4  2]]


In [73]:
second_row = rand_array[1]  # Get second row (row index 1)

sample = np.random.choice(second_row, size=5, replace=True)
print("Random sample from the second row (with replacement):", sample)


Random sample from the second row (with replacement): [ 1  1 20 20 20]


In [75]:
ordered_array_1 = np.array(range(1, 26))
ordered_array_1 = ordered_array_1.reshape(5,5)
print(ordered_array_1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [77]:
third_column = ordered_array_1[:, 2]

sample_col = np.random.choice(third_column, size=5, replace=False)
print(sample_col)


[23 13 18  8  3]
